FROM python:3.9.18-slim


WORKDIR /mlflow

RUN pip install mlflow

ENV BACKEND_URI sqlite:///mlflow.db

EXPOSE 5000

# host needs to be adjusted
CMD mlflow ui --backend-store-uri $BACKEND_URI --host 0.0.0.0