FROM apache/airflow:2.7.1

#updates pip
RUN pip install -U pip --upgrade pip

# copies in the requirements.txt file
COPY requirements.txt /requirements.txt

# executes the requirement installation
RUN pip install --no-cache-dir --user -r /requirements.txt